package com.personal.utility.model.ptlf.object.auth;

import com.personal.utility.model.ptlf.object.DateObject;
import com.personal.utility.model.ptlf.object.TimeObject;
import com.personal.utility.model.ptlf.object.auth.authobj.AcctObject;
import com.personal.utility.model.ptlf.object.auth.authobj.CrtauthObject;
import com.personal.utility.model.ptlf.object.auth.authobj.PreauthObject;
import com.personal.utility.model.ptlf.object.auth.authobj.RefrObject;
import com.personal.utility.model.ptlf.object.auth.authobj.RefrindObject;
import com.personal.utility.model.ptlf.object.auth.authobj.TrancdeObject;
import com.personal.utility.model.ptlf.object.auth.authobj.Userfld4Object;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class AuthObject {
    private DateObject tran_dat;
    private TimeObject tran_tim;
    private DateObject post_dat;
    private DateObject acq_ichg_setl_dat;
    private DateObject iss_ichg_setl_dat;
    private CrtauthObject crt_auth; 
    private TrancdeObject tran_cde;
    private AcctObject acct;
    private Userfld4Object user_fld4_mult_crncy;
    private RefrObject refr;
    private RefrindObject refr_ind;
    private TimeObject orig_tran_tim;
    private PreauthObject pre_auth_ts;

    private String typ;
    private String rte_stat;
    private String originator;
    private String responder;
    private String iss_cde;
    private String entry_tim;
    private String exit_tim;
    private String re_entry_tim;
    private String seq_num;
    private String term_name_loc;
    private String term_owner_name;
    private String term_city;
    private String term_st;
    private String term_cntry_cde;
    private String brch_id;
    private String user_fld2;
    private String term_tim_ofst;
    private String acq_inst_id_num;
    private String rcv_inst_id_num;
    private String term_typ;
    private String clerk_id;
    private String retl_sic_cde;
    private String orig;
    private String dest;
    private String crd_typ;
    private String resp_cde;
    private String amt_1;
    private String amt_2;
    private String exp_dat;
    private String track2;
    private String pin_ofst;
    private String pre_auth_seq_num;
    private String invoice_num;
    private String orig_invoice_num;
    private String authorizer;
    private String auth_ind;
    private String shift_num;
    private String batch_seq_num;
    private String apprv_cde;
    private String apprv_cde_lgth;
    private String ichg_resp;
    private String pseudo_term_id;
    private String rfrl_phone;
    private String dft_capture_flg;
    private String setl_flag;
    private String rvrl_cde;
    private String rea_for_chrgbck;
    private String num_of_chrgbck;
    private String pt_srv_cond_cde;
    private String pt_srv_entry_mde;
    private String auth_ind2;
    private String orig_crncy_cde;
    private String adj_setl_impact_flg;
    private String frwd_inst_id_num;
    private String crd_accpt_id_num;
    private String crd_iss_id_num;
    private String orig_msg_typ;
    private String orig_tran_dat;
    private String orig_seq_num;
    private String orig_b24_post_dat;
    private String excp_rsn_cde;
    private String ovrrde_flg;
    private String addr;
    private String zip_cde;
    private String addr_vrfy_stat;
    private String pin_ind;
    private String pin_tries;
    private String pre_auth_hlds_lvl;
    private String user_fld5;
    private String user_data;
}
